### ISSUE TITLE
tanium_all_asset_capture sample truncated

### ISSUE THREAD

**Issue by jkuepker** [administrativetrick/cribl-tanium-events#1]
It looks like the sample for "tanium_all_asset_capture" was truncated somehow.
I get the error "Unexpected end of JSON input" when clicking the sample after loading the pack
<img width="238" alt="CleanShot 2022-01-27 at 09 15 16@2x" src="https://user-images.githubusercontent.com/20614147/151376626-79319a1c-1ec1-4508-9650-5f893b7b14e8.png">
.

**Comment by administrativetrick** [comment]
This should work as expected now. Please update from git to check and let me know if it works. If it does I will close out this issue.
